# Generated by Django 4.2.27 on 2025-12-25 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'tweet')},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('FIRE', '🔥'), ('TROPHY', '🏆'), ('FLAG', '🏁'), ('ROCKET', '🚀'), ('CRASH', '💥')], max_length=20),
        ),
    ]
